---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/9strands-testing-organization/backstage-sample-quarkus-app-gitops